name: Tasks Synchronisation

on:
  workflow_dispatch:  # Manueller Trigger
  repository_dispatch:  # API-Trigger
    types: [update_tasks]

permissions:
  contents: write
  id-token: write

jobs:
  sync-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Update Tasks
        run: |
          # Erstelle tasks-Ordner falls nicht vorhanden
          mkdir -p tasks
          
          # Lese die aktuelle data.json oder erstelle sie
          if [ -f "tasks/data.json" ]; then
            echo "Bestehende Daten gefunden"
            # Lese den Inhalt aus dem client_payload
            if [ -n "${{ github.event.client_payload.content }}" ]; then
              echo '${{ github.event.client_payload.content }}' > tasks/data.json
              echo "Daten aktualisiert"
            fi
          else
            if [ -n "${{ github.event.client_payload.content }}" ]; then
              echo '${{ github.event.client_payload.content }}' > tasks/data.json
            else
              echo "[]" > tasks/data.json
            fi
            echo "Neue data.json erstellt"
          fi
          
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add tasks/data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update tasks via GitHub Action" && git push) 