name: Tasks Synchronisation

on:
  workflow_dispatch:  # Manueller Trigger
  repository_dispatch:  # API-Trigger
    types: [update_tasks]

jobs:
  sync-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Update Tasks
        env:
          GITHUB_TOKEN: ${{ secrets.TASKS_TOKEN }}
        run: |
          # Lese die aktuelle data.json
          if [ -f "tasks/data.json" ]; then
            echo "Bestehende Daten gefunden"
          else
            echo "[]" > tasks/data.json
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add tasks/data.json
            git commit -m "Initialisiere tasks/data.json"
            git push
          fi
          
      - name: Commit and Push if Changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add tasks/data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update tasks" && git push) 